/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.a6friends;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.lang.NumberFormatException;
import javax.swing.JOptionPane;
/**

/**
 *
 * @author briyi
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principall
     */
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCleanFields = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel3.setText("Number");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRead.setText("Search");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCleanFields.setText("Clean Fields");
        btnCleanFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanFieldsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCleanFields))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnRead)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnCleanFields))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

try {
    
    
                    String newName = String.valueOf(txtName.getText());
                    
                    long newNumber = Long.parseLong(txtNumber.getText());

                    String nameNumberString;
                    String name;
                    long number;
                    int index;

                    File file = new File("C:\\\\Mensajes\\\\A6friends.txt");

                    if (file.exists() == false) {                      
                        
                           file.createNewFile();
                    }
                    
                    
                    RandomAccessFile raf = new RandomAccessFile(file, "rw");
                    boolean found = false;

                    while (raf.getFilePointer() < raf.length()) {
                          
                            nameNumberString = raf.readLine();
                            String[] lineSplit = nameNumberString.split("!");

                            name = lineSplit[0];
                            number = Long.parseLong(lineSplit[1]);
                            
                            if (name.equals(newName) || number == newNumber) {
                                    found = true;
                                    break;
                            }
                    }
                    
                    if (found == false) {

                            nameNumberString = newName + "!" + String.valueOf(newNumber);
                            raf.writeBytes(nameNumberString);
                            raf.writeBytes(System.lineSeparator());                           
                            JOptionPane.showMessageDialog(null, " Friend added.");
                            txtName.setText("");
                            txtNumber.setText("");                           
                            raf.close();
                    }
                    
                    
                    else {                          
                            raf.close();
                            JOptionPane.showMessageDialog(null, "The contact exists. ");
                            txtName.setText("");
                            txtNumber.setText("");
                            
                    }
            }

            catch (IOException ioe) {

                    System.out.println(ioe);
                    JOptionPane.showMessageDialog(null, "An error has occurred creating/opening the file. ");
                    txtName.setText("");
                    txtNumber.setText("");
            }
            catch (NumberFormatException nef) {

                    System.out.println(nef);
                    JOptionPane.showMessageDialog(null, "A number format has ocurred");
                    txtName.setText("");
                    txtNumber.setText("");
            } 
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    
    try {
        String newName = String.valueOf(txtName.getText());
        long newNumber = Long.parseLong(txtNumber.getText());

        String nameNumberString;
        String name;
        int index;

        File file = new File("C:\\Mensajes\\A6friends.txt");

        if (!file.exists()) {
            file.createNewFile();
        }

        RandomAccessFile raf = new RandomAccessFile(file, "rw");
        boolean found = false;

        while (raf.getFilePointer() < raf.length()) {
            nameNumberString = raf.readLine();

            if (nameNumberString == null || nameNumberString.trim().isEmpty()) {
                continue;
            }

            String[] lineSplit = nameNumberString.split("!");
            if (lineSplit.length < 2) {
                continue;
            }

            name = lineSplit[0];

            if (name.equals(newName)) {
                found = true;
                break;
            }
        }

        if (found) {
            File tmpFile = new File("C:\\Mensajes\\temp.txt");
            RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");

            raf.seek(0);

            while (raf.getFilePointer() < raf.length()) {
                nameNumberString = raf.readLine();

                if (nameNumberString == null || nameNumberString.trim().isEmpty()) {
                    continue;
                }

                index = nameNumberString.indexOf('!');
                if (index == -1) continue;

                name = nameNumberString.substring(0, index);

                if (name.equals(newName)) {
                    nameNumberString = name + "!" + String.valueOf(newNumber);
                }

                tmpraf.writeBytes(nameNumberString);
                tmpraf.writeBytes(System.lineSeparator());
            }

            raf.seek(0);
            tmpraf.seek(0);

            while (tmpraf.getFilePointer() < tmpraf.length()) {
                raf.writeBytes(tmpraf.readLine());
                raf.writeBytes(System.lineSeparator());
            }

            raf.setLength(tmpraf.length());

            tmpraf.close();
            raf.close();
            tmpFile.delete();

            JOptionPane.showMessageDialog(null, "Friend updated.");
            txtName.setText("");
            txtNumber.setText("");

        } else {
            raf.close();
            JOptionPane.showMessageDialog(null, "Input name does not exist.");
            txtName.setText("");
            txtNumber.setText("");
        }

    } catch (IOException ioe) {
        System.out.println(ioe);
    } catch (NumberFormatException nef) {
        JOptionPane.showMessageDialog(null, "Invalid number format.");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed

    private void btnCleanFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanFieldsActionPerformed
        txtName.setText("");
        txtNumber.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_btnCleanFieldsActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        try {

                        String nameNumberString;
                        String name;
                        String searchName = String.valueOf(txtName.getText());

                        long number;
                        boolean found = false;
                        

                        File file = new File("C:\\\\Mensajes\\\\A6friends.txt");

                        if (!file.exists()) {
                                file.createNewFile();
                        }


                        RandomAccessFile raf = new RandomAccessFile(file, "rw");
                        
                        while (raf.getFilePointer() < raf.length()) {
                                nameNumberString = raf.readLine();
                                String[] lineSplit = nameNumberString.split("!");
                                name = lineSplit[0];
                                number = Long.parseLong(lineSplit[1]);

                                if (name.equals(searchName)) {
                                    txtName.setText(String.valueOf(name));
                                    txtNumber.setText(String.valueOf(number));
                                    found = true;
                                    raf.close();
                                    JOptionPane.showMessageDialog(null, "the name was found");
                                }   

                        }
                        if (found == false){
                                JOptionPane.showMessageDialog(null, "the name was not found");
                                txtName.setText("");
                                txtNumber.setText("");
                                raf.close();
                            }
                        
                    }
                        
                        
                        catch (IOException ioe)
                        {
                                JOptionPane.showMessageDialog(null, "An error has occurred");
                            
                        }
                        catch (NumberFormatException nef)
                        {
                                JOptionPane.showMessageDialog(null, "A Number Format error has ocurred");
                               
                        }
                        

    }//GEN-LAST:event_btnReadActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
                                           
    try {
        
        String deleteName = String.valueOf(txtName.getText());
        
        String nameNumberString;
        String name;
        long number;
        int index;

        
        File file = new File("C:\\Mensajes\\A6friends.txt");

        if (!file.exists()) {
            file.createNewFile();
        }

        RandomAccessFile raf = new RandomAccessFile(file, "rw");
        boolean found = false;

        
        while (raf.getFilePointer() < raf.length()) {
            nameNumberString = raf.readLine();

           
            if (nameNumberString == null || nameNumberString.trim().isEmpty()) {
                continue; 
            }
            
            String[] lineSplit = nameNumberString.split("!");
            
            
            if (lineSplit.length < 2) {
                continue;
            }
            // ---------------------------------------

            name = lineSplit[0];
            

            if (name.equals(deleteName)) {
                found = true;
                break;
            }
        }

        
        if (found == true) {
            
            
            File tmpFile = new File("C:\\Mensajes\\temp.txt");
            RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");

            
            raf.seek(0);

            
            while (raf.getFilePointer() < raf.length()) {
                nameNumberString = raf.readLine();

              
                if (nameNumberString == null || nameNumberString.trim().isEmpty()) {
                    continue; 
                }
                
                index = nameNumberString.indexOf('!');
                if (index == -1) continue; 

                name = nameNumberString.substring(0, index);

               
                if (name.equals(deleteName)) {
                    continue; 
                }

                
                tmpraf.writeBytes(nameNumberString);
                tmpraf.writeBytes(System.lineSeparator());
            }

            
            raf.seek(0);
            tmpraf.seek(0);

            
            while (tmpraf.getFilePointer() < tmpraf.length()) {
                raf.writeBytes(tmpraf.readLine());
                raf.writeBytes(System.lineSeparator());
            }

            
            raf.setLength(tmpraf.length());

            
            tmpraf.close();
            raf.close();
            tmpFile.delete();

            JOptionPane.showMessageDialog(null, "The contact was deleted.");
            txtName.setText("");
            txtNumber.setText("");

        } else {
            
            raf.close();
            JOptionPane.showMessageDialog(null, "Input name does not exist.");
            txtName.setText("");
            txtNumber.setText("");
        }

    } catch (IOException ioe) {
        System.out.println(ioe);
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanFields;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
